### ISSUE TITLE
Не сохраняется сортировка при пролистывании страниц

### ISSUE THREAD

**Issue by kravchenko-d** [CaseLabJS/CaseLab2024-team3#62]
При пролистывании страниц документов в DataTable2 не сохраняются параметры сортировки.

Также сортировка происходит только для документов текущей страницы. Но в таком виде функционал сортировки едва ли полезен.

Например, у пользователя 52 документа.
Если зайти на страницу "Мои документы" и отсортировать их по убыванию даты, то на первой строке мы не увидим самый свежий документ из 52. Мы увидим самый свежий документ из тех 20, которые оказались на 1-й странице.

**Comment by Coreytaz** [comment]
Нужно подвязать сортировку с бэкендом, а также привязать сортировку с queryparams
![image](https://github.com/user-attachments/assets/ae73e133-02da-4d29-ba04-1f096fe17705)
