### ISSUE TITLE
Не работает редактирование документа через меню в таблице документов

### ISSUE THREAD

**Issue by kravchenko-d** [CaseLabJS/CaseLab2024-team3#66]
![image](https://github.com/user-attachments/assets/87d33559-6241-4679-a332-b8ef39f927f6)

![image](https://github.com/user-attachments/assets/9201b206-e35b-4fce-ab49-6561106d9092)

**Comment by 45ark62** [comment]
Предлагаю вообще убрать редактирование с таблицы,ибо у нас всё тоже самое есть при клике на документ.А не работает,потому что при методе put  отправляет только название документа,хотя еще атрибутов куча.
Если вы считаете,что функционал дополнительного редактирования в таблице важен,то я могу починить

**Comment by 45ark62** [comment]
Исправлено
